// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/go-swagger/go-swagger/examples/go-usersclient/models"
)

// AddUserReader is a Reader for the AddUser structure.
type AddUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAddUserCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAddUserBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewAddUserDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAddUserCreated creates a AddUserCreated with default headers values
func NewAddUserCreated() *AddUserCreated {
	return &AddUserCreated{}
}

/* AddUserCreated describes a response with status code 201, with default header values.

Created
*/
type AddUserCreated struct {
}

// IsSuccess returns true when this add user created response has a 2xx status code
func (o *AddUserCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add user created response has a 3xx status code
func (o *AddUserCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add user created response has a 4xx status code
func (o *AddUserCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this add user created response has a 5xx status code
func (o *AddUserCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this add user created response a status code equal to that given
func (o *AddUserCreated) IsCode(code int) bool {
	return code == 201
}

func (o *AddUserCreated) Error() string {
	return fmt.Sprintf("[POST /users][%d] addUserCreated ", 201)
}

func (o *AddUserCreated) String() string {
	return fmt.Sprintf("[POST /users][%d] addUserCreated ", 201)
}

func (o *AddUserCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddUserBadRequest creates a AddUserBadRequest with default headers values
func NewAddUserBadRequest() *AddUserBadRequest {
	return &AddUserBadRequest{}
}

/* AddUserBadRequest describes a response with status code 400, with default header values.

Name should be atleast 2 characters long
*/
type AddUserBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this add user bad request response has a 2xx status code
func (o *AddUserBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this add user bad request response has a 3xx status code
func (o *AddUserBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add user bad request response has a 4xx status code
func (o *AddUserBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this add user bad request response has a 5xx status code
func (o *AddUserBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this add user bad request response a status code equal to that given
func (o *AddUserBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *AddUserBadRequest) Error() string {
	return fmt.Sprintf("[POST /users][%d] addUserBadRequest  %+v", 400, o.Payload)
}

func (o *AddUserBadRequest) String() string {
	return fmt.Sprintf("[POST /users][%d] addUserBadRequest  %+v", 400, o.Payload)
}

func (o *AddUserBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *AddUserBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddUserDefault creates a AddUserDefault with default headers values
func NewAddUserDefault(code int) *AddUserDefault {
	return &AddUserDefault{
		_statusCode: code,
	}
}

/* AddUserDefault describes a response with status code -1, with default header values.

error
*/
type AddUserDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the add user default response
func (o *AddUserDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this add user default response has a 2xx status code
func (o *AddUserDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this add user default response has a 3xx status code
func (o *AddUserDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this add user default response has a 4xx status code
func (o *AddUserDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this add user default response has a 5xx status code
func (o *AddUserDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this add user default response a status code equal to that given
func (o *AddUserDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *AddUserDefault) Error() string {
	return fmt.Sprintf("[POST /users][%d] add_User default  %+v", o._statusCode, o.Payload)
}

func (o *AddUserDefault) String() string {
	return fmt.Sprintf("[POST /users][%d] add_User default  %+v", o._statusCode, o.Payload)
}

func (o *AddUserDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *AddUserDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
