// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFindUsersParams creates a new FindUsersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindUsersParams() *FindUsersParams {
	return &FindUsersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindUsersParamsWithTimeout creates a new FindUsersParams object
// with the ability to set a timeout on a request.
func NewFindUsersParamsWithTimeout(timeout time.Duration) *FindUsersParams {
	return &FindUsersParams{
		timeout: timeout,
	}
}

// NewFindUsersParamsWithContext creates a new FindUsersParams object
// with the ability to set a context for a request.
func NewFindUsersParamsWithContext(ctx context.Context) *FindUsersParams {
	return &FindUsersParams{
		Context: ctx,
	}
}

// NewFindUsersParamsWithHTTPClient creates a new FindUsersParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindUsersParamsWithHTTPClient(client *http.Client) *FindUsersParams {
	return &FindUsersParams{
		HTTPClient: client,
	}
}

/* FindUsersParams contains all the parameters to send to the API endpoint
   for the find users operation.

   Typically these are written to a http.Request.
*/
type FindUsersParams struct {

	// Limit.
	Limit *int64

	// Name.
	Name *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindUsersParams) WithDefaults() *FindUsersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindUsersParams) SetDefaults() {
	var (
		limitDefault = int64(0)
	)

	val := FindUsersParams{
		Limit: &limitDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the find users params
func (o *FindUsersParams) WithTimeout(timeout time.Duration) *FindUsersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find users params
func (o *FindUsersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find users params
func (o *FindUsersParams) WithContext(ctx context.Context) *FindUsersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find users params
func (o *FindUsersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find users params
func (o *FindUsersParams) WithHTTPClient(client *http.Client) *FindUsersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find users params
func (o *FindUsersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the find users params
func (o *FindUsersParams) WithLimit(limit *int64) *FindUsersParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the find users params
func (o *FindUsersParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithName adds the name to the find users params
func (o *FindUsersParams) WithName(name *string) *FindUsersParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the find users params
func (o *FindUsersParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *FindUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
